// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtelqdwxjxxbrvwkuadr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0ZWxxZHd4anh4YnJ2d2t1YWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MTg3NDMsImV4cCI6MjA3NjM5NDc0M30.fhG4cEK4OU-4u8I_6A2a3CdwXWaHGjH63fwlV5daMRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});